version: '3.3'

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24

services:
  cerebro:
    image: polinux/cerebro
    environment:
      - ES_ADDRESS="es-ingest"
      - ES_PORT="9200"
      - ES_NAME="es-docker-ingest"
    ports:
      - "9000:9000"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
  
  es-ingest:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    container_name: es-ingest
    environment:
      - cluster.name=es-docker
      - node.name=es-ingest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/ingest.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    container_name: es-master-1
    environment:
      - cluster.name=es-docker
      - node.name=es-master-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11

  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    container_name: es-data-1
    environment:
      - cluster.name=es-docker
      - node.name=es-data-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9204:9200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12

  es-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.3
    container_name: es-data-2
    environment:
      - cluster.name=es-docker
      - node.name=es-data-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9205:9200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.13