cluster.name: "es-docker"
node.data: 'false'
node.master: 'false'
node.ingest: 'true'
network.host: 0.0.0.0
network.bind_host: 0.0.0.0
http.port: 9200
transport.tcp.compress: 'true'
discovery.zen.ping.unicast.hosts:
- 10.5.0.10
- 10.5.0.11
- 10.5.0.12
- 10.5.0.13
discovery.zen.minimum_master_nodes: 1
gateway.recover_after_nodes: 1
bootstrap.memory_lock: 'true'
indices.queries.cache.size: 30%
indices.memory.index_buffer_size: 40%
indices.fielddata.cache.size: 30%
indices.requests.cache.size: 2%